# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00e6bc22f23ca2f367f4a4648bac605716a4cc3ecdb969043e8af5ec63d1263272d4723387a1d5c47ce09e261ab399bd8f6d9289f99d331bf1e23b9abdd4ef53

test:
  secret_key_base: 5937fa78ca056fccd0353d045170de7994d7fa482a5a20b83261fefc85e37679afa68404af01f338811adf6a121fd49471a15df24818b92353d48a2d6c162468

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
